---
- hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: Start docker
    service: name=docker state=started

  - name: create docker image using PHP file
    command: docker build -t anandproj:PHPSite .
    args:
      chdir: /opt/source_code_git/project/php_site

  - name: create tag to image
    command: docker tag anandproj:PHPSite whitedevil2125/anandproj:PHPSite

  - name: Deploy Image for PHP in Test server
    command: docker run -d -p 8686:8000 anandproj:PHPSite
