From devopsedu/webapp
Maintainer Anand

#Install Apache
#RUN yum install httpd -y

#Copy Application Files
RUN rm -rf /var/www/html/*
COPY website /var/www/html/

#Open port 80
EXPOSE 8080

#Start Apache service
CMD ["/usr/sbin/apachectl", "-D", "FOREGROUND"]

